### PR TITLE
Add unique roles to authentication

### PR DESCRIPTION
**Pull request by nettob**
Add unique roles to token so the roles keep clean!

### CODE REVIEW

**Comment by Ener-Getick** [comment]
What's your use case?

**Comment by nettob** [comment]
None

**Comment by Ener-Getick** [comment]
I see this is more for performance. Why not :-)

Thank you @nettob

**Comment by Davidmattei** [comment]
Having a problem with this PR, my roles can also be Objects.
So I'm getting this error : **Error: Object of class X could not be converted to string**

Can we fix this by doing : $roles = array_unique($roles, **SORT_REGULAR**);

Greetings

**Comment by Ener-Getick** [comment]
Thank you @Davidmattei I fixed it in https://github.com/FriendsOfSymfony/FOSOAuthServerBundle/commit/0b25cdaae8983c630bb62d14b6993219b1dadb8d

**Comment by Davidmattei** [comment]
Thanks !

**Comment by nettob** [comment]
:+1:

**Comment by ruscon** [comment]
http://php.net/manual/en/function.array-unique.php

```
5.2.9	Added the optional sort_flags defaulting to SORT_REGULAR. Prior to 5.2.9, this function used to sort the array with SORT_STRING internally.
```

**Comment by Davidmattei** [comment]
@ruscon 

`5.2.10	Changed the default value of sort_flags back to SORT_STRING.`

**Pull request merged**
