### PR TITLE
The authorize form should be used only if authorize option true.

### PR DESCRIPTION
**Pull request by makasim**

### CODE REVIEW

**Comment by dkarlovi** [comment]
Why haven't our tests caught this?

**Comment by makasim** [comment]
I am build app on top of Symfony Flex, there is no forms and templating in my setup, things breaks here and there (:

**Comment by makasim** [comment]
Added tests

**Comment by dkarlovi** [comment]
This was previously done in #466, but since you've added tests, we should merge this one instead.

**Pull request merged**
