### PR TITLE
[EASY PR] Fixed Deprecation Warnings.

### PR DESCRIPTION
**Pull request by Sydney-o9**
- This simply fixed Symfony deprecation warnings.

Maintainers, please be awesome and review it so everyone's warnings can disappear!

### CODE REVIEW

**Comment by drekinov** [comment]
#599  and #598 seem duplicated. I hope someone merge any of three before November when symfony 5.0 is scheduled for release :)

**Comment by klapaudius** [comment]
Does FOS still alive ?

**Comment by alcaeus** [comment]
#598 and #599 are duplicated because branches weren't mergeable. I'll leave this PR open and take care of the deprecations soon.

**Comment by thomas-hiron** [comment]
Hi! Any updates on this?
Thanks

**Comment by deguif** [comment]
Closing as this was fixed with #648

**Pull request closed without merging**
