### PR TITLE
[WIP] Improved unit tests

### PR DESCRIPTION
**Pull request by dinamic**
As mentioned in #505, we need better unit tests so we can upgrade from one version of Symfony to the other with confidence. I will try to make things better one piece at a time, currently focussed on improving the unit tests. Some pieces are not really testable, so small scale refactoring would also occur.

This is a work in progress pull request.

I am creating it so people would know that I am working on the unit tests and we won't be working on the same thing at the same time.

### CODE REVIEW

**Comment by dkarlovi** [comment]
@dinamic love the idea, thank you. If you wish to support testing for Symfony 2.x, target branch 1.5.

**Comment by dinamic** [comment]
@wackyMole, makes sense. Just added the prefix to the title.

**Comment by dkarlovi** [comment]
There's an "In progress" label, but we don't have a bot on this project. :)

**Comment by dkarlovi** [comment]
You'll need to rebase, expect conflicts. Sorry about that.

**Comment by dinamic** [comment]
@dkarlovi, seems like the build are not passing because of the new CI stuff you set in.

It seems to require changes similar to this one:

```
         $this->request
             ->expects($this->once())
             ->method('getMethod')
             ->with()
-            ->willReturn('POST')
-        ;
+            ->willReturn('POST');
```

While I understand how this can benefit one line statements, I find it hard to believe it benefits multi-line statements. Can we have this rectified so we have a green build?

**Comment by dkarlovi** [comment]
You can make all the code match the coding style automatically if you just run `make` in the root of the project.

It will also run PHPStan and PHPUnit too so you're sure it will pass on CI if it passes for you.

**Comment by dkarlovi** [comment]
It's trying to change:

```php
         $this->request
             ->expects($this->once())
             ->method('getMethod')
             ->with()
             ->willReturn('POST')
         ;
```

to

```php
         $this->request
             ->expects($this->once())
             ->method('getMethod')
             ->with()
            ->willReturn('POST');
```

I'm not a fan of the dangling semicolon, but since I've adopted CS Fixer, I don't care what coding style the project uses, as long as it's enforced automatically, don't care either way.

I see CS discussions on unrelated PRs a HUGE waste of everyone's time.

**Comment by dinamic** [comment]
Yup, I can understand what it is trying to do. My point was that I fancy having the dangling semicolon. Makes it easy to comment single line, even the last one, without forcing you to add a semicolon on a new line or on the previous statement.

If you don't have a preference on this, could we have the CS changed to use my way?

**Comment by dkarlovi** [comment]
Absolutely, you can add `'multiline_whitespace_before_semicolons' => ['new_line_for_chained_calls']` to `.php_cs` and it should work.

We should do it in a separate PR though, so have all the changes be related to it.

**Comment by dinamic** [comment]
Just created a new PR with the PHPCS change - #510

**Comment by dkarlovi** [comment]
Merged, you can rebase and have your dangling semicolons. :+1:

**Comment by dkarlovi** [comment]
@dinamic do you think we can backport some of your effort back to 1.6, at least enough to make a Symfony v2/v3/v4 compatible release.

**Comment by dinamic** [comment]
I haven't done any major changes, so we should be able to do that. The only problem being that master is merged in and it dropped some compatibility I think.

**Comment by dkarlovi** [comment]
Can we cherry-pick commits into a PR to 1.6?

**Comment by dinamic** [comment]
@dkarlovi, for the most part we should be able to do it. Things will get complicated afterwards.

I would propose to review the current progress in this PR and have it merged to master. Meanwhile I could cherry-pick some of the initial changes and try to rebase them upon the 1.5 branch.

What do you think?

**Comment by dkarlovi** [comment]
Agreed.

I see you've merged your own semicolon branch and master. Usually you don't want to do that, you pull master and then rebase on top of it, this way the history is more clean and we avoid multiple merge commits.

Can you squash / reapply your commits and rebase on top of current master?

**Comment by dinamic** [comment]
I could do that, but I am not that savvy with git. :-/

I use SourceTree. If you can point me to a documentation that I can read on how to do what you have asked me, I would gladly do it.

**Comment by dkarlovi** [comment]
You can undo your commits in Git while your actual changes stay in place. With this, people developed a certain way of doing things on Github, called a [Github flow](https://guides.github.com/introduction/flow/).

**Copy / paste your entire project folder before you try this.**

Something like this:
```
# make sure your changes are already on Github, if something bad happens
git push

# adds this repo as your "upstream" remote (remotes are an important concept in Git)
git remote add upstream https://github.com/FriendsOfSymfony/FOSOAuthServerBundle.git

# to make sure you have the latest upstream/master
git fetch upstream

# this will remove all the commits in the current branch until it finds where you've forked master
# but leaves changes in place, uncommited
git reset upstream/master

# at this point your branch should be in sync with master, but you have your changes too
# commit as you did until now

# will say your local and remote branch differ, that's OK as you have just rewritten your history
# some "1984." stuff going on here :)
git status

# make your local changes overwrite your remote changes
# by which making your new history the actual history
git push --force


# at this point, this PR will contain your NEW history without anything else needed
```

What's important is you can do this as much as you like, always rewriting whatever happened previously.

**Comment by dkarlovi** [comment]
Also, if you're thinking about learning Git properly, there's a book [Pro Git](https://git-scm.com/book/en/v2) which I recommend. You only really need the first 3-4 chapters to get going, it's written well and it's completely free. :+1:

**Comment by dkarlovi** [comment]
Ignore me closing the PR, there were two buttons close together, quite confusing. :see_no_evil:

**Comment by dinamic** [comment]
This all makes sense, but squashing all the changes into one would also include the changes we don't want in the 1.6. Shouldn't we first separate the commits and then squash them into their own branches and PRs?

**Comment by dkarlovi** [comment]
You don't need to squash into one commit. When you reset, it's up to you how you reapply the commits, you can have as many of them as you like.

If we're cherry-picking, commits going to 1.6 must be stand-alone, obviously. Also note that, if we're back-porting, you'd first push the relevant commits to 1.6, we'd merge there and then I'd merge 1.6 to master. That way, you don't need to have them in this PR at all as they'd already be here.

If all of this is too confusing, we can just merge to master, 1.6 is only a stop-gap for people stuck with Symfony 2.

**Comment by dinamic** [comment]
It's not confusing. I have made a PR for the 1.6 unit tests - have a look at #512.

**Comment by dkarlovi** [comment]
This is waiting for #517

**Comment by dkarlovi** [comment]
@dinamic can you rebase on top of master and continue here? Your commits should follow the latest one in master, you can probably squash quite a bit of them.

**Comment by dinamic** [comment]
@dkarlovi, just rebased. Thanks for the suggestion! I still find it hard to determine when to use rebase and when to use merge. What's you take on this?

Changes in this PR seem rather minimalistic as most work was done in #512.

**Comment by dkarlovi** [comment]
>  still find it hard to determine when to use rebase and when to use merge. What's you take on this?

If you manage to rebase on top of master (and not merge), your commits can be applied cleanly as if they were made directly in master, git history is **much** cleaner by doing it. Rebase is preferable to merge in almost all situations, but takes getting used to.

> Changes in this PR seem rather minimalistic as most work was done and merged in #512 for 1.6 branch and merged to master in #517, #525 and #527.

We can always close this PR then.

**Comment by dinamic** [comment]
Agreed.

**Pull request closed without merging**
