### PR TITLE
Merge 1.6 to master

### PR DESCRIPTION
**Pull request by dinamic**
This is a continuation on #517, but with commits squashed.

### CODE REVIEW

**Comment by dinamic** [comment]
ping @dkarlovi

**Comment by dkarlovi** [comment]
@dinamic I don't know what happened here, but you seem to have squashed too much, there are my commits (which are already in master) here too.

You should:

1. checkout master
2. merge 1.6 (this gives you all the commits from 1.6 and a merge commit)
3. add the changes (needed to get the build green after having merged this) in one commit

You're not supposed to squash stuff already in 1.6.

**Comment by dinamic** [comment]
Yup, I overdid it. I have squashed some of my commits that went into 1.6 already.

In a recent conversation in #517 you said that:

> 1.x will get no further updates at all, we'll almost never need to merge 1.x to master. When we get to functional SF4 support, we'll release and move all development effort to 2.x

So, I figured I may as well squash some more commits to keep git history cleaner.

Looking at the diff is looks fine to me. Is it okay to be merged like this?

**Comment by dkarlovi** [comment]
Would you be OK with me cherry-picking your commits and rebasing on top of master?

**Comment by dinamic** [comment]
Yes, sounds good to me.

**Comment by dkarlovi** [comment]
OK, I'll do that later today. Leave this branch as is, I'll push to it and merge this PR.

**Comment by dkarlovi** [comment]
Merged in #527.

**Pull request closed without merging**
